### ISSUE TITLE
"Access denied to reports"

### ISSUE THREAD

**Issue by Denzerson1** [spianmo/GeoLocation#5]
![image](https://github.com/spianmo/GeoLocation/assets/130482776/829f73b7-7d7e-4915-8bac-04de0cb1da8c)

can you help me?

**Comment by Cancy126** [comment]
你可以尝试打开win10设置里的位置获取开关，可以解决上述问题。
这套代码获取位置信息，如果想要获取较为精确的位置信息，你需要打开wifi功能。否则位置偏移较大，这是windows提供的功能而不是这套代码可以控制。
微软提供的位置信息，是采用WGS84坐标系，这点很重要，一些国家会采用本国的地图坐标系，如果不了解，将会发现有500米左右的误差。

**Comment by spianmo** [comment]
> ![image](https://private-user-images.githubusercontent.com/130482776/242384347-829f73b7-7d7e-4915-8bac-04de0cb1da8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NzczMjcsIm5iZiI6MTcwNDY3NzAyNywicGF0aCI6Ii8xMzA0ODI3NzYvMjQyMzg0MzQ3LTgyOWY3M2I3LTdkN2UtNDkxNS04YmFjLTA0ZGUwY2IxZGE4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMTIzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGRiNzc4NTJlODAxOTgyYmY2MjAwMjk3NzRkNTljODdkNDJlZmIyNjZkNjA0MzQ0Yzg1NzA4M2E2OTk3MGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7a4p5vplOYjGUvIOJ4tiflvUuei4bvphi6GIXjsqnpM)
> 
> can you help me?

Because your windows does not have the positioning switch turned on, or your application is not allowed to perform GPS positioning, you can force the Windows positioning switch to be turned on by adding a registry. You can complete the addition of the registry in MFC, but please note that UAC permissions are required.

```bat
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\Privacy\LetAppsAccessLocation\ /f /v Value /t REG_DWORD /d 0 >nul
```

Location logs including Windows systems can also be cleared through the registry.

```bat
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location\NonPackaged /f >nul
```

A normal business logic for using GPS positioning on Windows is: first determine whether the system contains a GPS sensor. If the current computer does not contain a GPS sensor, it will prompt that the device does not support GPS positioning. Then determine whether the positioning switch of Windows is turned on. If it is not turned on, it will prompt first. First enable GPS permissions or actively increase UAC and then enable the system's positioning function by modifying the registry.

I can give a sample code in C#, which is similar in C++

```c#
    public static void PassLocationPermission()
    {
        RegistryKey localKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, Environment.Is64BitOperatingSystem ? RegistryView.Registry64 : RegistryView.Registry32);
        RegistryKey LetAppsAccessLocation = localKey.OpenSubKey(@"SOFTWARE\Microsoft\PolicyManager\default\Privacy\LetAppsAccessLocation", true);
        LetAppsAccessLocation.SetValue("Value", "1", RegistryValueKind.DWord);
        LetAppsAccessLocation.Close();
    }

    public static void ClearLocationRecord()
    {
        RegistryKey LocationRecord = Registry.CurrentUser.OpenSubKey(@"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location\", true);
        LocationRecord.DeleteSubKeyTree("NonPackaged", false);
        LocationRecord.Close();

    }
```

It is worth mentioning that this library is the core implementation of GPS positioning in the current C# core library. The implementation of the Geolocation function in chromium79 is also similar. Currently, there is no other good way to obtain positioning on Windows except using ATL COM to interact with the position sensor to obtain the position.

@Cancy126 @Denzerson1

**Comment by spianmo** [comment]
As @Cancy126 mentioned, whether to turn on the positioning switch of Windows will affect whether the positioning function can be used normally. However, there is a problem. Whether to use AGPS has nothing to do with turning on the positioning switch. AGPS is also automatically selected by the system after the Windows positioning switch is turned on. Yes, AGPS will be used when the GPS signal is poor (please refer to Microsoft official documentation[[Location API - Win32 apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/locationapi/windows-location-api-portal)](https://learn.microsoft.com/en-us/windows/win32/locationapi/windows-location-api-portal)] on this). 

Similarly, if the Windows location switch is not turned on, you can actually obtain the approximate geographical location through IP. This part needs to be coded by yourself.

**Comment by Cancy126** [comment]
多谢您的回复，问题我已经解决了。

**Comment by Denzerson1** [comment]
> 多谢您的回复，问题我已经解决了。

你具体是怎么解决的？您是否设法获得准确的位置作为坐标？你能展示代码如何做到这一点吗

**Comment by spianmo** [comment]
> > 多谢您的回复，问题我已经解决了。
> 
> 你具体是怎么解决的？您是否设法获得准确的位置作为坐标？你能展示代码如何做到这一点吗

`Readme`中的`Usage`和`main.cpp`中都有示例，关于为什么获取不到位置，详见上方我的reply，本身windows是不带权限申请的，只是系统会有GPS开关，如何强制开启GPS的开关上方的reply中也解释了具体怎么做。
